### ISSUE TITLE
check https://github.com/j0k3r/php-readability

### ISSUE THREAD

**Issue by younes0** [a7y/readability-php#1]
You might not have checked this one
https://github.com/j0k3r/php-readability

**Comment by a7y** [comment]
Thanks for bringing that repo to my attention.

If you look, however, the code is quite different between the two.

I'll have to do some testing to see which fork produces better results. It's probable that I'd migrate my apps to use j0k3r's library if it is indeed superior.

**Comment by younes0** [comment]
Keep me updated then please :)
Note that my tests showed that j0k3r's library performed better than https://github.com/codelucas/newspaper
